Calculator UI
brenpardal/CalculatorKotlin pull request #1
Opened 2021-01-18 19:02 UTC by brenpardal

Implementation of a simple calculator layout design

#### App preview - Nexus S
![Nexus_S](https://user-images.githubusercontent.com/73835964/104954104-6b070f00-59a6-11eb-949c-ae784d7fadbb.png)

#### App preview - Pixel 2 XL
![Pixel_2XL](https://user-images.githubusercontent.com/73835964/104954167-840fc000-59a6-11eb-997e-f36ab87d9d04.png)

2021-01-18 19:12 UTC, BQuinteros approved these changes

2021-01-18 19:20 UTC, SartiMau requested changes

2021-01-18 19:20 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/text_marginTop"
you can add this marginTop property into the OperationStyle

2021-01-18 19:20 UTC, SartiMau commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_numeric_width">0dp</dimen>
when the width or the height is 0dp you should put it on the XML, not in a dimen

2021-01-18 20:52 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="@dimen/text_marginTop"
Solved.

2021-01-18 20:53 UTC, brenpardal commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_numeric_width">0dp</dimen>
Solved. Thanks!

2021-01-18 21:20 UTC, SartiMau approved these changes

2021-01-18 21:21 UTC, BQuinteros approved these changes

2021-01-19 12:04 UTC, mauroLonghi commented on app/src/main/res/values/colors.xml
> +    <color name="background">#EFF2F4</color>
pls rename this resource please because it not representative

2021-01-19 12:10 UTC, mauroLonghi commented on app/src/main/res/values/strings.xml
> +    <string name="error_division_by_zero">ERROR, cannot divide by zero</string>
warning, please remember that this PR only include UI functionality, so this string they are over :
<string name="insert_operation_hint">Insert operation...</string>
    <string name="error_invalid_operation">ERROR, invalid operation</string>
    <string name="error_division_by_zero">ERROR, cannot divide by zero</string>

2021-01-19 12:52 UTC, brenpardal commented on app/src/main/res/values/colors.xml
> +    <color name="background">#EFF2F4</color>
Solved, background_text_view replaced by background_display

2021-01-19 12:55 UTC, brenpardal commented on app/src/main/res/values/strings.xml
> +    <string name="error_division_by_zero">ERROR, cannot divide by zero</string>
Solved.

2021-01-19 13:22 UTC, lucianoeli commented on app/src/main/res/layout/activity_main.xml
> +    android:id="@+id/view"
do you need to declare this id? remember that is not neccessary if you are not going to reference it

2021-01-19 13:24 UTC, lucianoeli approved these changes

2021-01-19 13:34 UTC, mauroLonghi commented on app/src/main/res/values/colors.xml
> +    <color name="background">#EFF2F4</color>
but you should remove this <color name="background">#EFF2F4</color>

2021-01-19 13:36 UTC, brenpardal commented on app/src/main/res/layout/activity_main.xml
> +    android:id="@+id/view"
Solved. Deleted view id

2021-01-19 13:50 UTC, brenpardal commented on app/src/main/res/values/colors.xml
> +    <color name="background">#EFF2F4</color>
It's the main container background,  I renamed it :D

2021-01-19 14:07 UTC, mauroLonghi approved these changes

2021-01-19 14:08 UTC, BQuinteros approved these changes

2021-01-19 14:08 UTC, SartiMau approved these changes

2021-01-19 14:11 UTC, nicolbidone approved these changes

2021-01-19 14:24 UTC, merged