Calculator's basic operations
brenpardal/CalculatorKotlin pull request #3
Opened 2021-01-20 15:22 UTC by brenpardal

### **WHAT'S NEW**
**This update includes:**
*  Calculator's basic operations
*  Error when a number is divided by zero
*  Error when user enter an invalid operation
*  Remove last symbol when "C" is pressed (short click)
*  Clear all when "C" is pressed (long click)

![basic_operations](https://user-images.githubusercontent.com/73835964/105195614-8fcfc380-5b19-11eb-8e0c-a280326ac7f8.gif)

2021-01-20 15:28 UTC, nicolbidone commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +import com.calculatorkt.utils.*
pls avoid using wildcards 
change the setting at
File > Settings > Project Settings > Code Style > Kotlin> Imports > General > Class count to use import with '*'

2021-01-20 15:33 UTC, SartiMau requested changes

2021-01-20 15:33 UTC, SartiMau commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +    override fun getErrorEnum() = errorEnum
if you put the variable public you can use the native get and remove this method

2021-01-20 15:33 UTC, SartiMau commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +        return EMPTY_STRING
why does this method need to return something?

2021-01-20 15:42 UTC, brenpardal commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +import com.calculatorkt.utils.*
Solved. Thanks!

2021-01-20 15:47 UTC, BQuinteros commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +        if (!firstOperand.isEmpty()) if (operator.isEmpty() && secondOperand.isEmpty()) {
Here you can do return if like you did it with when

2021-01-20 15:47 UTC, BQuinteros commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +        partialRes = firstOperand + operator + secondOperand
now in kotlin you can do this "$firstOperand$operator$secondOperand" is more efficient

2021-01-20 15:52 UTC, brenpardal commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +    override fun getErrorEnum() = errorEnum
Yes, you're right! Solved.

2021-01-20 16:00 UTC, brenpardal commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +        partialRes = firstOperand + operator + secondOperand
Yes! Thanks. Solved.

2021-01-20 16:01 UTC, brenpardal commented on app/src/main/java/com/calculatorkt/mvp/model/CalculatorModel.kt
> +        return EMPTY_STRING
Solved. Deleted method. I pass EMPTY_STRING and use only reset().

2021-01-20 16:42 UTC, SartiMau approved these changes

2021-01-20 17:46 UTC, mauroLonghi approved these changes

2021-01-20 18:26 UTC, lucianoeli approved these changes

2021-01-21 12:03 UTC, BQuinteros approved these changes

2021-01-21 12:12 UTC, nicolbidone approved these changes

2021-01-21 12:14 UTC, merged